## Importing Required Libraries

In [1]:
import pandas as pd, numpy as np, seaborn as sns, matplotlib.pyplot as plt
import sklearn
import os
import PIL

from matplotlib import image
from PIL import Image
from PIL import ImageDraw, ImageFont
from PIL import ImageEnhance
from PIL import ImageFilter


## Preprocessing

In [25]:
animals = ['donkeys','Horses']

for i in animals:
    folder_dir = (r"C:\Users\sreya\OneDrive\venom\Image\{}".format(i))
    
    for j in os.listdir(folder_dir):
        
        if i == "donkeys":
            imagePil = Image.open(f"{folder_dir}\{j}")
            imageResized = imagePil.resize((32,32))
            imageColE = ImageEnhance.Color(imageResized)
            gray_image = imageColE.enhance(0)
            gray_image.save(r"C:\Users\sreya\OneDrive\venom\pictures\mules\{}.jpg".format(j))
          
        
        elif i == "Horses":
            imagePil = Image.open(f"{folder_dir}\{j}")
            imageResized = imagePil.resize((32,32))
            imageColE = ImageEnhance.Color(imageResized)
            gray_image = imageColE.enhance(0)
            gray_image.save(r"C:\Users\sreya\OneDrive\venom\pictures\horses\{}.jpg".format(j))

## Converting to DataFrames

In [31]:
animals = ['mules','horses']
list_np = []


for i in animals:
    folder_path = (r"C:\Users\sreya\OneDrive\venom\pictures\{}".format(i))
    
    for j in os.listdir(folder_path):
        image = Image.open(f"{folder_path}\{j}")
        imageNp = np.array(image)
        image_flatten = imageNp.flatten()
        
        list_np.append(np.append(image_flatten,i))
 

data = pd.DataFrame(list_np,dtype=object)
data.rename(columns = {3072:'animal'}, inplace = True)
data
        

0    1    2    3    4    5    6    7    8    9  ... 3063 3064 3065  \
0      97   97   97   84   84   84   78   78   78   84  ...  116  116  116   
1     124  124  124   99   99   99  104  104  104   97  ...  135  135  135   
2     126  126  126  135  135  135  134  134  134  119  ...  135  135  135   
3     159  159  159  161  161  161  169  169  169  165  ...  183  183  183   
4     138  138  138   99   99   99   68   68   68   84  ...   88   88   88   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
2011  185  185  185  185  185  185  185  185  185  185  ...  203  203  203   
2012   49   49   49   49   49   49   47   47   47   47  ...   88   88   88   
2013   58   58   58   56   56   56   52   52   52   47  ...  198  198  198   
2014  114  114  114  142  142  142  176  176  176  221  ...   60   60   60   
2015  193  193  193  186  186  186  188  188  188  200  ...   55   55   55   

     3066 3067 3068 3069 3070 3071  animal  
0     117  117  117  117  117  117   mules  
1     110  110  110  140  140  140   mules  
2     151  151  151  172  172  172   mules  
3     176  176  176  150  150  150   mules  
4      94   94   94  109  109  109   mules  
...   ...  ...  ...  ...  ...  ...     ...  
2011  211  211  211  205  205  205  horses  
2012  108  108  108  124  124  124  horses  
2013  221  221  221  211  211  211  horses  
2014   63   63   63   58   58   58  horses  
2015   50   50   50   70   70   70  horses  

[2016 rows x 3073 columns]

## Creating a logistic Regression Model

In [33]:
## Defining X and Y

x = data.iloc[:,:-1]
y = data['animal']

In [34]:
# Spliting the data into train and test

from sklearn.model_selection import train_test_split

xTrain, xTest, yTrain, yTest = train_test_split(x,y,
                                                test_size= 0.32)

xTrain.shape, xTest.shape, len(yTrain), len(yTest)

((1370, 3072), (646, 3072), 1370, 646)

In [37]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score as acs
from sklearn.metrics import confusion_matrix


# Training the model
LR = LogisticRegression(max_iter=6000)
LR.fit(xTrain,yTrain)

C:\Users\sreya\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=6000)

In [38]:
# Predicting the values

lr_yTrainPred = LR.predict(xTrain)
lr_yTestPred = LR.predict(xTest)

## Checking the accuracy score
acs(yTrain,lr_yTrainPred), acs(yTest,lr_yTestPred)

(1.0, 0.5092879256965944)

In [39]:
## Checking the confusion matrix

confusion_matrix(yTrain,lr_yTrainPred), confusion_matrix(yTest,lr_yTestPred)

(array([[719,   0],
        [  0, 651]], dtype=int64),
 array([[177, 150],
        [167, 152]], dtype=int64))

## Creating a Decision Tree model 

In [40]:
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
dtc.fit(xTrain,yTrain)

DecisionTreeClassifier()

In [41]:
dtc_yTrainPred = dtc.predict(xTrain)
dtc_yTestPred = dtc.predict(xTest)

## Checking the accuracy score
acs(yTrain,dtc_yTrainPred), acs(yTest,dtc_yTestPred)

(1.0, 0.5371517027863777)

In [42]:
confusion_matrix(yTrain,dtc_yTrainPred), confusion_matrix(yTest,dtc_yTestPred)

(array([[719,   0],
        [  0, 651]], dtype=int64),
 array([[185, 142],
        [157, 162]], dtype=int64))