In [1]:
import pandas as pd,numpy as np,re
import sklearn
import nltk
from nltk.corpus import stopwords

In [2]:
data = pd.read_csv(r"C:\Users\sreya\OneDrive\venom\EDA\starbucks.csv")

In [3]:
datac = data.copy()

In [4]:
datac=datac.drop('Unnamed: 0',axis=1)

In [5]:
datac

Location        date              Designation  \
0            Hyderabad, AP  2015-05-05  Assistant Store Manager   
1                    Texas  2023-04-30                  Barista   
2              Chicago, IL  2023-04-30               Mixologist   
3     Midtown New York, NY  2023-04-30                  Barista   
4          Albuquerque, NM  2023-04-30                  Barista   
...                    ...         ...                      ...   
7015           Toronto, ON  2022-03-19         Shift Supervisor   
7016        Schaumburg, IL  2022-03-19         Shift Supervisor   
7017             Bronx, NY  2022-03-19                  Barista   
7018           Toronto, ON  2022-03-19                  Barista   
7019         Hollywood, FL  2022-03-18                  Barista   

                                            Title  \
0                           Good work envioroment   
1                    Very stressful and UNDERPAID   
2                           Little accountability   
3                                Worst Management   
4                                            Fun    
...                                           ...   
7015         Stressful But decent pay for student   
7016  Fun place to work with incredible benefits    
7017                                         Good   
7018                  Could be great or horrible    
7019                         Fun place to work at   

                                                 Review  Rating  
0     1- Good company to work as its tata.\r2- New c...     4.0  
1     It’s a very stressful environment. Dealing wit...     1.0  
2     Little to no accountability. You can be a hard...     4.0  
3     Worked with 3 store managers during my 9 month...     2.0  
4     I really enjoyed working here for like 2 years...     4.0  
...                                                 ...     ...  
7015  Customers were challenging and often rude. Co ...     3.0  
7016  Good place to work while going to school and a...     4.0  
7017  Okay job lot of space to move up in company go...     3.0  
7018  Honestly it totally depends on the manager and...     3.0  
7019  Great for college students.Flexible hours and ...     5.0  

[7020 rows x 6 columns]

### Converting to lowercase

In [6]:
def convertLowerCase(x):
    return x.str.lower()

datac['Review'] = convertLowerCase(datac['Review'])
datac.head()

Location        date              Designation  \
0         Hyderabad, AP  2015-05-05  Assistant Store Manager   
1                 Texas  2023-04-30                  Barista   
2           Chicago, IL  2023-04-30               Mixologist   
3  Midtown New York, NY  2023-04-30                  Barista   
4       Albuquerque, NM  2023-04-30                  Barista   

                          Title  \
0         Good work envioroment   
1  Very stressful and UNDERPAID   
2         Little accountability   
3              Worst Management   
4                          Fun    

                                              Review  Rating  
0  1- good company to work as its tata.\r2- new c...     4.0  
1  it’s a very stressful environment. dealing wit...     1.0  
2  little to no accountability. you can be a hard...     4.0  
3  worked with 3 store managers during my 9 month...     2.0  
4  i really enjoyed working here for like 2 years...     4.0

### Remove html tags

In [7]:
def removeHtmlTags(text):
    return re.sub(r'<.*?>','', text)

datac['Review'] = datac['Review'].apply(removeHtmlTags)
datac.head()

Location        date              Designation  \
0         Hyderabad, AP  2015-05-05  Assistant Store Manager   
1                 Texas  2023-04-30                  Barista   
2           Chicago, IL  2023-04-30               Mixologist   
3  Midtown New York, NY  2023-04-30                  Barista   
4       Albuquerque, NM  2023-04-30                  Barista   

                          Title  \
0         Good work envioroment   
1  Very stressful and UNDERPAID   
2         Little accountability   
3              Worst Management   
4                          Fun    

                                              Review  Rating  
0  1- good company to work as its tata.\r2- new c...     4.0  
1  it’s a very stressful environment. dealing wit...     1.0  
2  little to no accountability. you can be a hard...     4.0  
3  worked with 3 store managers during my 9 month...     2.0  
4  i really enjoyed working here for like 2 years...     4.0

## Remove urls

In [8]:
def removeUrls(text):
    return re.sub(r'https?://\S+|www\.S\+', '', text)

datac['Review'] = datac['Review'].apply(removeUrls)
datac.head()

Location        date              Designation  \
0         Hyderabad, AP  2015-05-05  Assistant Store Manager   
1                 Texas  2023-04-30                  Barista   
2           Chicago, IL  2023-04-30               Mixologist   
3  Midtown New York, NY  2023-04-30                  Barista   
4       Albuquerque, NM  2023-04-30                  Barista   

                          Title  \
0         Good work envioroment   
1  Very stressful and UNDERPAID   
2         Little accountability   
3              Worst Management   
4                          Fun    

                                              Review  Rating  
0  1- good company to work as its tata.\r2- new c...     4.0  
1  it’s a very stressful environment. dealing wit...     1.0  
2  little to no accountability. you can be a hard...     4.0  
3  worked with 3 store managers during my 9 month...     2.0  
4  i really enjoyed working here for like 2 years...     4.0

In [9]:
datac['Review'][0]

'1- good company to work as its tata.\r2- new company\r3- good to learn new things.\r4- all full timer\r5- good culture \r6- chance to learn about coffee'

### handle new lines(\n and \r)

In [10]:
def handleNewLine(text):
    return re.sub(r'\n|\r',' ', text)

datac['Review'] = datac['Review'].apply(handleNewLine)
datac.head()

Location        date              Designation  \
0         Hyderabad, AP  2015-05-05  Assistant Store Manager   
1                 Texas  2023-04-30                  Barista   
2           Chicago, IL  2023-04-30               Mixologist   
3  Midtown New York, NY  2023-04-30                  Barista   
4       Albuquerque, NM  2023-04-30                  Barista   

                          Title  \
0         Good work envioroment   
1  Very stressful and UNDERPAID   
2         Little accountability   
3              Worst Management   
4                          Fun    

                                              Review  Rating  
0  1- good company to work as its tata. 2- new co...     4.0  
1  it’s a very stressful environment. dealing wit...     1.0  
2  little to no accountability. you can be a hard...     4.0  
3  worked with 3 store managers during my 9 month...     2.0  
4  i really enjoyed working here for like 2 years...     4.0

### Remove special chars/punctuations

In [11]:
def removeSpecialChars(text):
    return re.sub('[^0-9a-zA-Z]',' ', text)

datac['Review'] = datac['Review'].apply(removeSpecialChars)
datac.head()

Location        date              Designation  \
0         Hyderabad, AP  2015-05-05  Assistant Store Manager   
1                 Texas  2023-04-30                  Barista   
2           Chicago, IL  2023-04-30               Mixologist   
3  Midtown New York, NY  2023-04-30                  Barista   
4       Albuquerque, NM  2023-04-30                  Barista   

                          Title  \
0         Good work envioroment   
1  Very stressful and UNDERPAID   
2         Little accountability   
3              Worst Management   
4                          Fun    

                                              Review  Rating  
0  1  good company to work as its tata  2  new co...     4.0  
1  it s a very stressful environment  dealing wit...     1.0  
2  little to no accountability  you can be a hard...     4.0  
3  worked with 3 store managers during my 9 month...     2.0  
4  i really enjoyed working here for like 2 years...     4.0

### Remove Stopwords

In [27]:
def removeStopwords(text):

    a = []
    for word in text.split():
        if word not in stopwords.words('english'):
              a.append(word)
    return ' '.join(a)




In [28]:
datac['Review'] = datac['Review'].apply(removeStopwords)
datac.head()

Location        date              Designation  \
0         Hyderabad, AP  2015-05-05  Assistant Store Manager   
1                 Texas  2023-04-30                  Barista   
2           Chicago, IL  2023-04-30               Mixologist   
3  Midtown New York, NY  2023-04-30                  Barista   
4       Albuquerque, NM  2023-04-30                  Barista   

                          Title  \
0         Good work envioroment   
1  Very stressful and UNDERPAID   
2         Little accountability   
3              Worst Management   
4                          Fun    

                                              Review  Rating  \
0  1 good company work tata 2 new company 3 good ...     4.0   
1  stressful environment dealing people think ent...     1.0   
2  little accountability hard worker burnt manage...     4.0   
3  worked 3 store managers 9 month tenure starbuc...     2.0   
4  really enjoyed working like 2 years managers p...     4.0   

                                        reviewTokens  
0  [1, , good, company, work, tata, , 2, , new, c...  
1  [stressful, environment, , dealing, people, th...  
2  [little, accountability, , hard, worker, burnt...  
3  [worked, 3, store, manager, 9, month, tenure, ...  
4  [really, enjoyed, working, like, 2, year, , ma...

### Lemmatization

In [14]:
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.stem import WordNetLemmatizer
lem = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\sreya\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\sreya\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


### Converting to lem tokens

In [29]:
def lemTokens(text):
    lemTokens = []
    for word in text.split(' '):

        if word != ' ' or word != '':
              lemTokens.append(lem.lemmatize(word))
    
    return lemTokens

In [31]:
datac['reviewTokens'] = datac['Review'].apply(lemTokens)

In [33]:
datac.head()

Location        date              Designation  \
0         Hyderabad, AP  2015-05-05  Assistant Store Manager   
1                 Texas  2023-04-30                  Barista   
2           Chicago, IL  2023-04-30               Mixologist   
3  Midtown New York, NY  2023-04-30                  Barista   
4       Albuquerque, NM  2023-04-30                  Barista   

                          Title  \
0         Good work envioroment   
1  Very stressful and UNDERPAID   
2         Little accountability   
3              Worst Management   
4                          Fun    

                                              Review  Rating  \
0  1 good company work tata 2 new company 3 good ...     4.0   
1  stressful environment dealing people think ent...     1.0   
2  little accountability hard worker burnt manage...     4.0   
3  worked 3 store managers 9 month tenure starbuc...     2.0   
4  really enjoyed working like 2 years managers p...     4.0   

                                        reviewTokens  
0  [1, good, company, work, tata, 2, new, company...  
1  [stressful, environment, dealing, people, thin...  
2  [little, accountability, hard, worker, burnt, ...  
3  [worked, 3, store, manager, 9, month, tenure, ...  
4  [really, enjoyed, working, like, 2, year, mana...

### Converting the reviewTokens into sentence

In [34]:
datac["lemsentances"]=datac["reviewTokens"].str.join(' ')

In [35]:
datac.head()

Location        date              Designation  \
0         Hyderabad, AP  2015-05-05  Assistant Store Manager   
1                 Texas  2023-04-30                  Barista   
2           Chicago, IL  2023-04-30               Mixologist   
3  Midtown New York, NY  2023-04-30                  Barista   
4       Albuquerque, NM  2023-04-30                  Barista   

                          Title  \
0         Good work envioroment   
1  Very stressful and UNDERPAID   
2         Little accountability   
3              Worst Management   
4                          Fun    

                                              Review  Rating  \
0  1 good company work tata 2 new company 3 good ...     4.0   
1  stressful environment dealing people think ent...     1.0   
2  little accountability hard worker burnt manage...     4.0   
3  worked 3 store managers 9 month tenure starbuc...     2.0   
4  really enjoyed working like 2 years managers p...     4.0   

                                        reviewTokens  \
0  [1, good, company, work, tata, 2, new, company...   
1  [stressful, environment, dealing, people, thin...   
2  [little, accountability, hard, worker, burnt, ...   
3  [worked, 3, store, manager, 9, month, tenure, ...   
4  [really, enjoyed, working, like, 2, year, mana...   

                                        lemsentances  
0  1 good company work tata 2 new company 3 good ...  
1  stressful environment dealing people think ent...  
2  little accountability hard worker burnt manage...  
3  worked 3 store manager 9 month tenure starbuck...  
4  really enjoyed working like 2 year manager pro...

### Spliting the data into train and test

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
x=datac[["lemsentances"]]
y=datac[["Rating"]]

xTrain,xTest,yTrain,yTest=train_test_split(x,y,
                                          test_size=0.2)

## Creating a model for countvectorizer

### For bag of unigrams

In [41]:
from sklearn.feature_extraction.text import CountVectorizer
countvectorizer=CountVectorizer()

In [42]:
unixTrain=countvectorizer.fit_transform(xTrain["lemsentances"])
unixTrain.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [43]:
unixTest=countvectorizer.transform(xTest["lemsentances"])
unixTest.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## Creating a logistic regression model

In [44]:

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score as acs
from sklearn.metrics import confusion_matrix

LR=LogisticRegression()

In [45]:
LR.fit(unixTrain,yTrain)

YTrainpred=LR.predict(unixTrain)
YTestpred=LR.predict(unixTest)

C:\Users\sreya\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sreya\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [46]:
# checking the accuracy score and confusion matrix
acs(yTrain,YTrainpred),acs(yTest,YTestpred)

(0.9011752136752137, 0.39173789173789175)

In [47]:
confusion_matrix(yTrain,YTrainpred),confusion_matrix(yTest,YTestpred)

(array([[ 602,    2,   12,    2,    7],
        [   2,  560,   38,   12,   13],
        [   3,    3, 1438,  102,   44],
        [   3,    0,   91, 1353,   94],
        [   1,    1,   47,   78, 1108]], dtype=int64),
 array([[ 57,  32,  46,  16,   6],
        [ 39,  30,  62,  30,  11],
        [ 39,  43, 161, 111,  49],
        [  9,  11,  90, 152, 102],
        [  2,   4,  42, 110, 150]], dtype=int64))

### For bag of uni-bi grams

In [48]:
countvectorizer=CountVectorizer(ngram_range=(1,2))

bixTrain=countvectorizer.fit_transform(xTrain["lemsentances"])
bixTrain.toarray()


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [49]:
bixTest=countvectorizer.transform(xTest["lemsentances"])
bixTest.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

## Creating a logistic regression model

In [50]:
LR.fit(bixTrain,yTrain)

YTrainpred=LR.predict(bixTrain)
YTestpred=LR.predict(bixTest)

C:\Users\sreya\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sreya\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [51]:
# checking the accuracy score and confusion matrix

acs(yTrain,YTrainpred),acs(yTest,YTestpred)

(0.999465811965812, 0.4031339031339031)

In [52]:
confusion_matrix(yTrain,YTrainpred),confusion_matrix(yTest,YTestpred)

(array([[ 625,    0,    0,    0,    0],
        [   0,  624,    1,    0,    0],
        [   0,    0, 1590,    0,    0],
        [   0,    0,    0, 1541,    0],
        [   0,    0,    1,    1, 1233]], dtype=int64),
 array([[ 51,  24,  65,   8,   9],
        [ 34,  28,  80,  23,   7],
        [ 32,  29, 182, 109,  51],
        [  3,   5,  98, 160,  98],
        [  3,   2,  49, 109, 145]], dtype=int64))

## Cretaing a model for TfidfVectorizer

### for TfidfVectorizer bag of unigrams

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfVec=TfidfVectorizer()

tfunixTrain=tfVec.fit_transform(xTrain["lemsentances"])
tfunixTrain.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [55]:
tfunixTest=tfVec.transform(xTest["lemsentances"])
tfunixTest.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## Creating a logistic regression model

In [56]:
LR.fit(tfunixTrain,yTrain)

YTrainpred=LR.predict(tfunixTrain)
YTestpred=LR.predict(tfunixTest)

C:\Users\sreya\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\sreya\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [57]:
# checking the accuracy score and confusion matrix

acs(yTrain,YTrainpred),acs(yTest,YTestpred)

(0.7168803418803419, 0.4180911680911681)

In [58]:
confusion_matrix(yTrain,YTrainpred),confusion_matrix(yTest,YTestpred)

(array([[ 422,   14,  149,   28,   12],
        [  40,  256,  242,   59,   28],
        [  22,    9, 1279,  187,   93],
        [   8,    1,  214, 1155,  163],
        [   2,    2,  121,  196,  914]], dtype=int64),
 array([[ 47,  16,  76,   9,   9],
        [ 24,  17, 103,  19,   9],
        [ 21,  18, 199, 119,  46],
        [  4,   1,  99, 171,  89],
        [  2,   2,  44, 107, 153]], dtype=int64))

### for TfidfVectorizer bag of uni-bi grams

In [59]:
tfVec=TfidfVectorizer(ngram_range = (1,2))

tfbixTrain=tfVec.fit_transform(xTrain["lemsentances"])
tfbixTrain.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [60]:
tfbixTest=tfVec.transform(xTrain["lemsentances"])
tfbixTest.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## Creating a logistic regression model

In [66]:
LR.fit(tfbixTrain,yTrain)

yTrainpred=LR.predict(tfbixTrain)
yTestpred=LR.predict(tfbixTest)

C:\Users\sreya\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [68]:
acs(yTrain,yTrainpred)

0.9024216524216524

In [69]:
confusion_matrix(yTrain,YTrainpred)

array([[ 513,    0,   89,   13,   10],
       [   0,  396,  174,   35,   20],
       [   0,    0, 1531,   32,   27],
       [   0,    0,   17, 1502,   22],
       [   0,    0,   58,   51, 1126]], dtype=int64)

## Conclusion

- For TfidfVectorizer accuracy score is low as compare to countvectorizer
- For countvectorizer accuracy score is pretty good for train data but very bad for test data